phrases
welcome
	self for: 'Welcome' translation: 'Welcome' locale: (WALocale language: 'en').
	self for: 'Welcome' translation: 'Welkom' locale: (WALocale language: 'nl').
	self for: 'Welcome' translation: 'Willkommen' locale: (WALocale language: 'de').
	self for: 'Welcome' translation: 'Velkommen' locale: (WALocale language: 'da').
	self for: 'Welcome' translation: 'Bienvenue' locale: (WALocale language: 'fr').
	self for: 'Welcome' translation: '歡迎光臨' locale: (WALocale language: 'cn').	
	self for: 'Welcome' translation: 'أهلاً و سهلاً' locale: (WALocale language: 'ar').
